### PR TITLE
added missing pygments lib to reqs file to fix crash on new ubuntu in…

### PR DESCRIPTION
**Pull request by grispan56**
…stalls

# Pull Request Template

## Description

after installing on a fresh ubuntu machine the app failed to start because of missing pygments library.
added pygments 2.2.0 to the requirements.txt so it will be installed automatically.

### CODE REVIEW

**Comment by deadbits** [comment]
Good catch. I'm add the pinned pygmentize repo ASAP.
In the meantime, "apt install pygmentize" or "pip install -U pygmentize" around this so you can install

**Comment by deadbits** [comment]
Thanks again for catching this again :)

**Comment by grispan56** [comment]
no problem, updated.
also had this error
omnibus >> whois 1.1.1.1

[!] Failed to load module (whois)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 1653, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/usr/local/lib/python2.7/dist-packages/cmd2.py", line 1848, in onecmd
    stop = func(statement)
  File "omnibus-cli.py", line 634, in do_whois
    result = self.dispatch.submit(self.session, 'whois', arg)
  File "/root/omnibus/lib/dispatch.py", line 131, in submit
    result = self.run(module, artifact)
  File "/root/omnibus/lib/dispatch.py", line 167, in run
    raise err
ImportError: No module named ipaddr
EXCEPTION of type 'ImportError' occurred with message: 'No module named ipaddr'

after running pip install ipaddr it gives the following:

omnibus >> whois 115.23.21.1
/usr/local/lib/python2.7/dist-packages/ipwhois/nir.py:443: UserWarning: NIRWhois._get_nets_krnic() has been deprecated and will be removed. You should now use NIRWhois.get_nets_krnic().
  warn('NIRWhois._get_nets_krnic() has been deprecated and will be '
[!] Caught unhandled exception: 'str' object does not support item assignment
{
    "asn": "4766"
}

**Comment by deadbits** [comment]
Hmm looks like I'm using a deprecated function.. I'm thinking this is probably a dependency from ipwhois. I'd have thought pip would solve depdencies like that during pip install IPWhois

I'll open another ticket to fix this bug just for proper tracking . thanks for this.
I've had some weird problems with this module too but mainly lack of results though not this error yet. Thanks for the info!

**Comment by deadbits** [comment]
Also just fyi I'm in the middle of a big refactor of how modules are executed, also adding tests, etc. Heading on a short vacation over this upcoming weekend but after that, back to the grind!
So this should be much more stable in the very near future. Sorry for any bugs in the meantime but thank you for reporting them!

**Pull request merged**
